# Generated by Django 4.2.3 on 2023-07-20 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, verbose_name='Round of')),
                ('currentBalance', models.DecimalField(blank=True, decimal_places=2, default=1000000, max_digits=15, verbose_name='Balance')),
                ('ended', models.BooleanField(default=False, verbose_name='Ended')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, editable=False, max_length=10)),
                ('unitprice', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('quantity', models.IntegerField(editable=False)),
                ('type', models.CharField(choices=[('NEW', 'Start a new game'), ('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('game', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='unique_game_per_user_per_month'),
        ),
    ]
