# Generated by Django 4.2.3 on 2023-07-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_currentbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Ended'),
        ),
        migrations.AlterField(
            model_name='game',
            name='currentBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000000, max_digits=15, verbose_name='Balance'),
        ),
    ]
